services:
  - type: web
    name: endo-detect-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 5000
    plan: free
    region: oregon
    rootDir: Website/backend


